### ISSUE TITLE
Installation fails.

### ISSUE THREAD

**Issue by rvlander** [mapd/pymapd#61]
Trying to install via `pip`:
```
pip install pymapd
Collecting pymapd
  Using cached pymapd-0.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-91aap1_o/pymapd/setup.py", line 108, in <module>
        **extra_kwargs
    NameError: name 'extra_kwargs' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-91aap1_o/pymapd/
```
Environment:
```
pip --version
pip 9.0.1 from <env_dir>/lib/python3.5/site-packages (python 3.5)
```

**Comment by TomAugspurger** [comment]
Whoops, should be fixed by https://github.com/mapd/pymapd/pull/62

FYI if you're on linux or mac, a workaround is to install Cython first.
